# Install Library yang diperlukan

In [24]:
!pip install tabula-py

Requirement already satisfied: tabula-py in c:\users\acer\anaconda3\lib\site-packages (2.9.0)
Requirement already satisfied: numpy in c:\users\acer\anaconda3\lib\site-packages (from tabula-py) (1.24.4)
Requirement already satisfied: distro in c:\users\acer\anaconda3\lib\site-packages (from tabula-py) (1.9.0)
Requirement already satisfied: pandas>=0.25.3 in c:\users\acer\anaconda3\lib\site-packages (from tabula-py) (1.4.4)
Requirement already satisfied: pytz>=2020.1 in c:\users\acer\anaconda3\lib\site-packages (from pandas>=0.25.3->tabula-py) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\acer\anaconda3\lib\site-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\acer\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas>=0.25.3->tabula-py) (1.12.0)

In [25]:
!pip install camelot

Collecting camelot
  Downloading Camelot-12.06.29.tar.gz (3.5 MB)
     ---------------------------------------- 3.5/3.5 MB 1.6 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting SQLAlchemy<0.8.0,>=0.7.7
  Downloading SQLAlchemy-0.7.10.tar.gz (3.5 MB)
     ---------------------------------------- 3.5/3.5 MB 2.2 MB/s eta 0:00:00

  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [84 lines of output]
  C:\Users\ACER\anaconda3\lib\site-packages\setuptools\dist.py:472: SetuptoolsDeprecationWarning: Invalid dash-separated options
  !!

          ********************************************************************************
          Usage of dash-separated 'description-file' will not be supported in future
          versions. Please use the underscore name 'description_file' instead.

          By 2024-Sep-26, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.

          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************

  !!
    opt = self.warn_dash_deprecation(opt, section)
  C:\Users\ACER\anaconda3\lib\site-packages\setuptools\dist.py:472: SetuptoolsDeprecationWarning: Invalid dash-separated options
  !!

          ********************************************************************************
          Usage of dash-separated 'author-email' will not be supported in future
          versions. Please use the underscore name 'author_email' instead.

          By 2024-Sep-26, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.

          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting Elixir>=0.7.1
  Downloading Elixir-0.7.1.tar.gz (47 kB)
     ---------------------------------------- 47.1/47.1 kB 2.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting sqlalchemy-migrate>=0.7.1
  Downloading sqlalchemy_migrate-0.13.0-py2.py3-none-any.whl (109 kB)
     -------------------------------------- 109.1/109.1 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: Jinja2>=2.5.5 in c:\users\acer\anaconda3\lib\site-packages (from camelot) (3.1.3)
Requirement already satisfied: chardet>=1.0.1 in c:\users\acer\anaconda3\lib\site-packages (from camelot) (3.0.4)
Collecting xlwt==0.7.2
  Downloading xlwt-0.7.2.zip (131 kB)
     -------------------------------------- 131.2/131.2 kB 1.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting xlrd==0.7.1
  Downloading xlrd-0.7.1.zip (125 kB)
     -------------------------------------- 125.4/125.4 kB 3.6 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\acer\anaconda3\lib\site-packages (from Jinja2>=2.5.5->camelot) (2.0.1)
Requirement already satisfied: decorator in c:\users\acer\anaconda3\lib\site-packages (from sqlalchemy-migrate>=0.7.1->camelot) (5.1.1)
Collecting Tempita>=0.4
  Downloading Tempita-0.5.2-py3-none-any.whl (12 kB)
Requirement already satisfied: sqlparse in c:\users\acer\anaconda3\lib\site-packages (from sqlalchemy-migrate>=0.7.1->camelot) (0.4.4)
Collecting sqlalchemy-migrate>=0.7.1
  Downloading sqlalchemy_migrate-0.12.0-py2.py3-none-any.whl (108 kB)
     -------------------------------------- 109.0/109.0 kB 2.1 MB/s eta 0:00:00
  Downloading sqlalchemy-migrate-0.11.0.tar.gz (128 kB)
     -------------------------------------- 128.3/128.3 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  !!
    opt = self.warn_dash_deprecation(opt, section)
  C:\Users\ACER\anaconda3\lib\site-packages\setuptools\dist.py:472: SetuptoolsDeprecationWarning: Invalid dash-separated options
  !!

          ********************************************************************************
          Usage of dash-separated 'home-page' will not be supported in future
          versions. Please use the underscore name 'home_page' instead.

          By 2024-Sep-26, you need to update your project and remove deprecated calls
          or your builds will no longer be supported.

          See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
          ********************************************************************************

  !!
    opt = self.warn_dash_deprecation(opt, section)
  C:\Users\ACER\anaconda3\lib\site-packages\setuptools\__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
  !!

          ********************************************************************************
          Requirements should be satisfied by a PEP 517 installer.
          If you are using pip, you can try `pip install --use-pep517`.
          ********************************************************************************

  !!
    dist.fetch_build_eggs(dist.setup_requires)
  C:\Users\ACER\anaconda3\lib\site-packages\setuptools\command\develop.py:39: EasyInstallDeprecationWarning: easy_install command is deprecated.
  !!

          ********************************************************************************
          Please avoid running ``setup.py`` and ``easy_install``.
          Instead, use pypa/build, pypa/installer or other
          standards-based tools.

          See https://github.com/pypa/setuptools/issues/917 for details.
          ********************************************************************************

  !!
    easy_install.initialize_options(self)
  C:\Users\ACER\anaconda3\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
  !!

          ********************************************************************************
          Please avoid running ``setup.py`` directly.
          Instead, use pypa/build, pypa/installer or other
          standards-based tools.

          See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
          ********************************************************************************

  !!
    self.initialize_options()
  error in setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
      pytz>=2010h
          ~~~~~~^
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Berikut adalah script untuk mengubah pdf lampiran profil kesehatan Jawa Barat jadi csv
Caveat: script setiap tahun berbeda karena halaman dan kerangka tabel berbeda-beda setiap tahunnya. Sehingga tidak dapat dilakukan automasi 
Feel free to give me any suggestions

In [9]:
# import library
import pdfplumber
import pandas as pd
import datetime as dt
import sys

## Scraping Data

In [30]:
import tabula

# Tenaga Puskemas

# Replace "nama_file.pdf" with your actual file path
df = tabula.read_pdf("2021.pdf", pages="43")[0]
df.replace("Ahli Teknologi Laboratorium", "Ahli Teknologi Laboratorium Medik", inplace=True)
df.replace("Dokter atau dokter layanan", "Dokter atau dokter layanan primer", inplace=True)
df['Jumlah Tenaga'] = df['Unnamed: 0']
df = df.dropna()
df.drop('Unnamed: 0', axis=1, inplace=True)
df['Jumlah Tenaga'] = df['Jumlah Tenaga'].astype(str)
df['Jumlah Tenaga'] = df['Jumlah Tenaga'].astype(str).str.rstrip('.0')
df['Jumlah Tenaga'] = df['Jumlah Tenaga'].str.replace(".", "")

# df['Jumlah Tenaga'] = df['Jumlah Tenaga']*1000
df['Jumlah Tenaga'] = df['Jumlah Tenaga'].astype(int)
df['tahun'] = "2021"
df['unit_kerja'] = "puskesmas"
df

<ipython-input-30-3314a8be3fa9>:14: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Jumlah Tenaga'] = df['Jumlah Tenaga'].str.replace(".", "")

               Jenis Tenaga Kesehatan  Jumlah Tenaga tahun unit_kerja
1   Dokter atau dokter layanan primer           2903  2021  puskesmas
3                         Dokter gigi            982  2021  puskesmas
4                             Perawat          12066  2021  puskesmas
5                               Bidan          16953  2021  puskesmas
6                  Tenaga Kefarmasian           1844  2021  puskesmas
7                       Tenaga Kesmas           1612  2021  puskesmas
8         Tenaga kesehatan Lingkungan           1076  2021  puskesmas
9                         Tenaga gizi           1132  2021  puskesmas
10  Ahli Teknologi Laboratorium Medik           1214  2021  puskesmas

In [11]:
# Tenaga Rumah Sakit

df = tabula.read_pdf("2021.pdf", pages="47")[0]
df['Jumlah Tenaga Kesehatan'] = df['Jumlah Tenaga Kesehatan'].astype(str)
df['Jumlah Tenaga Kesehatan'] = df['Jumlah Tenaga Kesehatan'].str.replace(".", "")
df['Jumlah Tenaga Kesehatan'] = pd.to_numeric(df['Jumlah Tenaga Kesehatan'], errors='coerce').fillna(0).astype(int)
df['tahun'] = "2021"
df['unit_kerja'] = "rumah sakit"
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Jenis Tenaga Kesehatan   9 non-null      object
 1   Jumlah Tenaga Kesehatan  9 non-null      int32
 2   tahun                    9 non-null      object
 3   unit_kerja               9 non-null      object
dtypes: int32(1), object(3)
memory usage: 380.0+ bytes

<ipython-input-11-a39eba9bc895>:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Jumlah Tenaga Kesehatan'] = df['Jumlah Tenaga Kesehatan'].str.replace(".", "")

In [21]:
## Rekapitulasi Rasio Tenaga Kesehatan /100.000

import camelot

tables = camelot.read_pdf("2021.pdf", flavor='stream', pages='48')

df = tables[0].df

df.columns = df.iloc[1]

df = df.iloc[2:]
df.reset_index(drop=True, inplace=True)
df = df.rename_axis(None, axis=1)
df['Ratio/100.000 Penduduk'] = df['Ratio/100.000 Penduduk'].astype(float)
df['tahun'] = "2021"
df

        Tenaga Kesehatan  Ratio/100.000 Penduduk tahun
0       Dokter Spesialis                   22.95  2021
1            Dokter Umum                   21.55  2021
2            Dokter Gigi                    5.30  2021
3                  Bidan                   56.54  2021
4                Perawat                  121.59  2021
5            Kefarmasian                   18.74  2021
6   Kesehatan Masyarakat                    4.42  2021
7   Kesehatan Lingkungan                    3.00  2021
8                   Gizi                    4.63  2021
9       Keterafian Fisik                    2.68  2021
10      Keteknisan Medis                    8.69  2021
11         Non Kesehatan                  111.58  2021

In [37]:
## Jumlah Fasilitas Kesehatan Menurut Kepemilikan 
tables = camelot.read_pdf("2021.pdf", flavor='stream', pages='158')

df = tables[0].df

df.columns = df.iloc[3]

df = df.iloc[9:,[1,32] ]
df = df.iloc[:-1,: ]

df.set_axis(["Kabupaten/Kota", "Jumlah"], axis=1, inplace=True)
df.reset_index(drop=True, inplace=True)

df['Jumlah'] = df['Jumlah'].str.replace("-", "0")
df['Jumlah'] = df['Jumlah'].replace('', '0')
df['Jumlah'] = df['Jumlah'].str.replace(",", "")
df['Jumlah'] = pd.to_numeric(df['Jumlah'], errors='coerce').fillna(0).astype(int)
df['tahun'] = "2021"
df

             Kabupaten/Kota  Jumlah tahun
0           Kabupaten Bogor    1251  2021
1        Kabupaten Sukabumi       0  2021
2         Kabupaten Cianjur       0  2021
3         Kabupaten Bandung      58  2021
4           Kabupaten Garut       6  2021
5     Kabupaten Tasikmalaya      10  2021
6          Kabupaten Ciamis       8  2021
7        Kabupaten Kuningan     103  2021
8         Kabupaten Cirebon      86  2021
9      Kabupaten Majalengka      27  2021
10       Kabupaten Sumedang       0  2021
11      Kabupaten Indramayu      77  2021
12         Kabupaten Subang      13  2021
13     Kabupaten Purwakarta       0  2021
14       Kabupaten Karawang      90  2021
15         Kabupaten Bekasi      62  2021
16  Kabupaten Bandung Barat       0  2021
17    Kabupaten Pangandaran       3  2021
18               Kota Bogor      57  2021
19            Kota Sukabumi      24  2021
20             Kota Bandung       0  2021
21             Kota Cirebon      45  2021
22              Kota Bekasi      98  2021
23               Kota Depok     107  2021
24              Kota Cimahi      69  2021
25         Kota Tasikmalaya      27  2021
26              Kota Banjar       3  2021
27               JAWA BARAT    2224  2021

In [61]:
### PELAYANAN KESEHATAN GIGI DAN MULUT MENURUT KECAMATAN DAN PUSKESMAS

tables = camelot.read_pdf("2021.pdf", flavor='stream', pages='227')

df = tables[0].df
df.columns = df.iloc[6]

df = df.iloc[7:,[1,3,4,6,8,10,12] ]
df.reset_index(drop=True, inplace=True)
df.iloc[27,0] = "Jawa Barat"
df.set_axis(["Kabupaten/Kota", "Jumlah Tumpatan Gigi Tetap", "Pencabutan Gigi Tetap", "Rasio Pencabutan", "Jumlah Kasus Gigi", "Jumlah Kasus dirujuk", "% Rasio Dirujuk"], axis=1, inplace=True)
df = df.replace('', '0')
df = df.replace('-', '0')
for col in ['Rasio Pencabutan', '% Rasio Dirujuk']:
    df[col] = df[col].str.replace(',', '.').astype(float)

for col in ['Jumlah Tumpatan Gigi Tetap', 'Pencabutan Gigi Tetap', 'Jumlah Kasus Gigi', 'Jumlah Kasus dirujuk']:
    df[col] = df[col].str.replace(',', '').astype(int)
df['tahun'] = "2021"
df['unit_kerja'] = "puskesmas"
df

,Kabupaten/Kota,Jumlah Tumpatan Gigi Tetap,Pencabutan Gigi Tetap,Rasio Pencabutan,Jumlah Kasus Gigi,Jumlah Kasus dirujuk,% Rasio Dirujuk,tahun,unit_kerja
0,Kabupaten Bogor,4551,5550,0.8,97907,3078,3.1,2021,puskesmas
1,Kabupaten Sukabumi,22238,1570,0.0,18948,1273,0.1,2021,puskesmas
2,Kabupaten Cianjur,2138,4010,0.5,26350,1232,4.7,2021,puskesmas
3,Kabupaten Bandung,6577,14350,0.5,142272,4717,3.3,2021,puskesmas
4,Kabupaten Garut,4271,10599,0.4,60914,2026,3.3,2021,puskesmas
5,Kabupaten Tasikmalaya,1385,3103,44.9,19722,308,1.6,2021,puskesmas
6,Kabupaten Ciamis,811,2533,0.3,22845,1575,0.1,2021,puskesmas
7,Kabupaten Kuningan,1035,1760,0.6,18203,2088,11.5,2021,puskesmas
8,Kabupaten Cirebon,2860,5032,0.6,70891,4440,0.6,2021,puskesmas
9,Kabupaten Majalengka,317,1150,27.6,31387,2288,7.3,2021,puskesmas
10,Kabupaten Sumedang,1525,2847,20.0,24567,1433,5.8,2021,puskesmas
11,Kabupaten Indramayu,30,24,1.3,0,950,0.0,2021,puskesmas
12,Kabupaten Subang,728,1238,0.6,21230,2603,0.1,2021,puskesmas
13,Kabupaten Purwakarta,1156,1717,0.7,23260,551,2.4,2021,puskesmas
14,Kabupaten Karawang,1214,2972,0.4,45728,704,1.5,2021,puskesmas
15,Kabupaten Bekasi,4652,3972,1.2,28607,1140,4.0,2021,puskesmas
16,Kabupaten Bandung Barat,145,628,0.2,6299,369,5.9,2021,puskesmas
17,Kabupaten Pangandaran,97,701,3.2,6292,449,5.1,2021,puskesmas
18,Kota Bogor,4523,1942,2.3,43339,2566,0.1,2021,puskesmas
19,Kota Sukabumi,214,807,0.3,14383,1401,9.7,2021,puskesmas
20,Kota Bandung,3343,2893,1.2,46557,7089,0.2,2021,puskesmas
21,Kota Cirebon,2815,1297,2.2,26273,1374,0.1,2021,puskesmas
22,Kota Bekasi,1680,2076,0.8,49532,2826,0.1,2021,puskesmas
23,Kota Depok,4220,1508,2.8,32709,4232,0.1,2021,puskesmas
24,Kota Cimahi,1263,949,31.9,19997,2028,0.1,2021,puskesmas
25,Kota Tasikmalaya,2989,3047,1.0,23566,757,3.2,2021,puskesmas
26,Kota Banjar,114,505,0.2,4478,182,4.1,2021,puskesmas
27,Jawa Barat,76891,78780,1.0,926256,53679,5.8,2021,puskesmas

In [38]:
## PELAYANAN KESEHATAN GIGI DAN MULUT PADA ANAK SD DAN SETINGKAT MENURUT JENIS KELAMIN, KECAMATAN, DAN PUSKESMAS

tables = camelot.read_pdf("2021.pdf", flavor='stream', pages='228')

df = tables[0].df
# df.columns = df.iloc[7]

df = df.iloc[8:, [1, 2, 4, 5, 7, 8, 9, 10, 11] + list(range(13, 23)) + [24,25,27,28,31]]
df = df.iloc[:-1,: ]

df.reset_index(drop=True, inplace=True)
df = df.rename_axis(None, axis=1)
df.iloc[27,0] = "Jawa Barat"
df.set_axis(['Kabupaten/Kota', 'jumlah_SD/MI','jumlah_SD/MI_SG_Massal','%jumlah_SD/MI_SG_Massal',
             'jumlah_SD/MI_LG','%jumlah_SD/MI_LG',
            'jumlah_murid_SD/MI_L', 'jumlah_murid_SD/MI_P', 'jumlah_murid_SD/MI_LP',
            'jumlah_murid_SD/MI_L_Diperiksa','%jumlah_murid_SD/MI_L_Diperiksa','jumlah_murid_SD/MI_P_Diperiksa','%jumlah_murid_SD/MI_P_Diperiksa', 'jumlah_murid_SD/MI_LP_Diperiksa','%jumlah_murid_SD/MI_LP_Diperiksa',
            'jumlah_murid_SD/MI_L_PR','jumlah_murid_SD/MI_P_PR','jumlah_murid_SD/MI_LP_PR',
            'jumlah_murid_SD/MI_L_MP','%jumlah_murid_SD/MI_L_MP','jumlah_murid_SD/MI_P_MP','%jumlah_murid_SD/MI_P_MP','jumlah_murid_SD/MI_LP_MP','%jumlah_murid_SD/MI_LP_MP'], axis=1, inplace=True)
df = df.replace('', '0')
df = df.replace('-', '0')
for col in df.columns[df.columns.str.contains('%')]:
    df[col] = df[col].str.replace(',', '.').astype(float)

for col in df.columns[~(df.columns.str.contains('%') | (df.columns == 'Kabupaten/Kota'))]:
    df[col] = df[col].str.replace(',', '').astype(int)
tahun = "2021"
df['tahun'] = tahun
df.to_csv(f"dataset/pelayanan_gigi_anaksd/{tahun}.csv", index=False)
df

,Kabupaten/Kota,jumlah_SD/MI,jumlah_SD/MI_SG_Massal,%jumlah_SD/MI_SG_Massal,jumlah_SD/MI_LG,%jumlah_SD/MI_LG,jumlah_murid_SD/MI_L,jumlah_murid_SD/MI_P,jumlah_murid_SD/MI_LP,jumlah_murid_SD/MI_L_Diperiksa,...,jumlah_murid_SD/MI_L_PR,jumlah_murid_SD/MI_P_PR,jumlah_murid_SD/MI_LP_PR,jumlah_murid_SD/MI_L_MP,%jumlah_murid_SD/MI_L_MP,jumlah_murid_SD/MI_P_MP,%jumlah_murid_SD/MI_P_MP,jumlah_murid_SD/MI_LP_MP,%jumlah_murid_SD/MI_LP_MP,tahun
0,Kabupaten Bogor,1699,1699,100.0,1643,96.7,113461,108524,221985,2508,...,1592,1485,3077,904,56.8,816,54.9,1720,55.9,2021
1,Kabupaten Sukabumi,1465,314,21.4,5472,373.5,87506,96103,183609,10276,...,3428,3601,7029,2392,69.8,2838,78.8,5230,74.4,2021
2,Kabupaten Cianjur,1188,79,6.6,0,0.0,0,0,0,0,...,0,0,0,0,0.0,0,0.0,0,0.0,2021
3,Kabupaten Bandung,1650,52,3.2,426,25.8,189097,191274,380371,14741,...,5550,5908,11458,1272,22.9,2136,36.2,3408,29.7,2021
4,Kabupaten Garut,1889,1744,92.3,1704,90.2,110836,109284,220120,28500,...,15993,14917,30910,5484,34.3,5595,37.5,2199,7.1,2021
5,Kabupaten Tasikmalaya,1311,455,34.7,885,67.5,16866,17013,33879,33775,...,10844,11203,22047,3980,36.7,4279,38.2,8259,37.5,2021
6,Kabupaten Ciamis,527,186,35.3,699,132.6,29705,31763,61468,12844,...,5493,5895,11386,2010,36.6,2016,34.2,4026,35.4,2021
7,Kabupaten Kuningan,741,226,30.5,539,72.7,46504,43385,89889,20860,...,4568,4939,9507,3330,72.9,3962,80.2,7292,76.7,2021
8,Kabupaten Cirebon,1065,0,0.0,1056,99.2,58276,57372,115648,27474,...,6411,5971,12382,2206,34.4,2255,37.8,4461,36.0,2021
9,Kabupaten Majalengka,697,226,32.4,688,64.6,53164,50666,103830,24490,...,5477,5684,11161,2515,45.9,2660,46.8,5175,46.4,2021
10,Kabupaten Sumedang,560,137,24.5,490,87.5,38698,40749,79447,10188,...,2772,2980,5752,1747,63.0,1934,64.9,3681,64.0,2021
11,Kabupaten Indramayu,615,163,26.5,442,71.9,0,0,0,0,...,0,0,18505,0,0.0,0,0.0,2748,14.9,2021
12,Kabupaten Subang,851,15,1.8,30,3.5,54001,58719,112720,704,...,151,149,300,97,64.2,59,39.6,156,52.0,2021
13,Kabupaten Purwakarta,461,288,62.5,421,91.3,45052,42884,87936,21610,...,6559,6223,12782,4530,69.1,4430,71.2,8960,70.1,2021
14,Kabupaten Karawang,1101,54,4.9,950,86.3,134559,130073,264632,10361,...,2094,2265,4359,1567,74.8,1687,74.5,3254,74.7,2021
15,Kabupaten Bekasi,1189,338,28.4,762,64.1,113935,117507,231442,34475,...,11087,10730,21817,5141,46.4,5268,49.1,10409,47.7,2021
16,Kabupaten Bandung Barat,892,18,2.0,1,0.1,14526,16457,30983,13895,...,0,0,13925,262,0.0,0,0.0,476,3.4,2021
17,Kabupaten Pangandaran,344,122,35.5,292,84.9,17495,16329,33824,7565,...,3399,3245,6644,853,25.1,393,12.1,1811,27.3,2021
18,Kota Bogor,342,56,16.4,267,78.1,45613,42514,88127,14950,...,6162,6599,12761,1709,27.7,2115,32.1,3824,30.0,2021
19,Kota Sukabumi,100,17,17.0,79,79.0,12132,11699,23831,7598,...,4230,4027,8257,438,10.4,541,13.4,979,11.9,2021
20,Kota Bandung,271,23,8.5,1292,476.8,43447,41154,84601,19473,...,6310,6547,12857,2497,39.6,2947,45.0,5444,42.3,2021
21,Kota Cirebon,184,0,0.0,184,100.0,19440,17889,37329,2088,...,2165,2735,4900,643,29.7,834,30.5,1477,30.1,2021
22,Kota Bekasi,801,0,0.0,67,8.4,141227,134936,276163,9674,...,3060,3254,6314,1735,56.7,1916,58.9,3651,57.8,2021
23,Kota Depok,583,48,8.2,453,77.7,103077,97879,200956,41335,...,17657,18333,35990,4520,25.6,5144,28.1,9664,26.9,2021
24,Kota Cimahi,146,14,9.6,71,48.6,25367,24550,49917,6873,...,3073,2729,5802,401,13.0,524,19.2,925,15.9,2021
25,Kota Tasikmalaya,282,209,74.1,262,92.9,37565,40139,77704,13662,...,6394,6461,12855,3456,54.1,3467,53.7,6923,53.9,2021
26,Kota Banjar,111,72,64.9,117,105.4,10732,10359,21091,4048,...,1129,1335,2464,733,64.9,678,50.8,1411,57.3,2021
27,Jawa Barat,21065,6555,31.1,19292,91.6,1562281,1549221,3111502,393967,...,135598,137215,305241,54422,40.1,58494,42.6,107563,35.2,2021

In [39]:
## Jumlah Tenaga Medis Per Kab/Kota Puskesmaas
tables = camelot.read_pdf("2021.pdf", flavor='stream', pages='183')

df = tables[0].df

df = df.iloc[:36,[1, 19,21,23,25,27,29] ]
df = df.iloc[9: ]
df.set_axis(['Kab/Kota','jml_dg_l','jml_dg_p','jml_dg_lp','jml_dgsp_l','jml_dgsp_p','jml_dgsp_lp'], axis=1, inplace=True)
df = df.replace('', '0')
df = df.replace('-', '0')

for col in df.columns[~(df.columns.str.contains('%') | (df.columns == 'Kab/Kota'))]:
    df[col] = df[col].str.replace(',', '').astype(int)

df

,Kab/Kota,jml_dg_l,jml_dg_p,jml_dg_lp,jml_dgsp_l,jml_dgsp_p,jml_dgsp_lp
9,Kabupaten Bogor,6,62,68,0,0,0
10,Kabupaten Sukabumi,10,19,29,0,0,0
11,Kabupaten Cianjur,15,51,66,0,0,0
12,Kabupaten Bandung,11,62,73,0,0,0
13,Kabupaten Garut,7,21,28,0,0,0
14,Kabupaten Tasikmalaya,6,15,21,0,0,0
15,Kabupaten Ciamis,6,21,27,0,0,0
16,Kabupaten Kuningan,5,11,16,0,0,0
17,Kabupaten Cirebon,11,32,43,0,0,0
18,Kabupaten Majalengka,7,11,18,0,0,0
19,Kabupaten Sumedang,3,15,18,0,0,0
20,Kabupaten Indramayu,7,25,32,0,0,0
21,Kabupaten Subang,6,25,31,1,0,1
22,Kabupaten Purwakarta,4,13,17,0,0,0
23,Kabupaten Karawang,8,30,38,0,0,0
24,Kabupaten Bekasi,4,42,46,0,0,0
25,Kabupaten Bandung Barat,7,26,33,0,0,0
26,Kabupaten Pangandaran,6,6,12,1,1,2
27,Kota Bogor,1,45,46,0,0,0
28,Kota Sukabumi,5,7,12,0,0,0
29,Kota Bandung,12,77,89,0,0,0
30,Kota Cirebon,8,35,43,0,0,0
31,Kota Bekasi,7,78,85,0,0,0
32,Kota Depok,1,47,48,1,1,2
33,Kota Cimahi,0,17,17,0,0,0
34,Kota Tasikmalaya,4,18,18,0,0,0
35,Kota Banjar,2,6,8,0,0,0

In [40]:
# Menggabungkan kolom 'jml_dg_l', 'jml_dg_p', 'jml_dgsp_l', dan 'jml_dgsp_p' menjadi satu kolom 'jumlah'
df_dg = pd.concat([
    df.loc[:,['Kab/Kota','jml_dg_l']].rename(columns={'jml_dg_l':'jumlah'}).assign(jns_kelamin='laki-laki', profesi='dokter gigi', unit_kerja='puskesmas'),
    df.loc[:,['Kab/Kota','jml_dg_p']].rename(columns={'jml_dg_p':'jumlah'}).assign(jns_kelamin='perempuan', profesi='dokter gigi', unit_kerja='puskesmas'),
    df.loc[:,['Kab/Kota','jml_dgsp_l']].rename(columns={'jml_dgsp_l':'jumlah'}).assign(jns_kelamin='laki-laki', profesi='dokter gigi spesialis', unit_kerja='puskesmas'),
    df.loc[:,['Kab/Kota','jml_dgsp_p']].rename(columns={'jml_dgsp_p':'jumlah'}).assign(jns_kelamin='perempuan', profesi='dokter gigi spesialis', unit_kerja='puskesmas')
], ignore_index=True)

# Menghapus duplikat dan mengurutkan data berdasarkan 'Kab/Kota' dan 'jns_kelamin'
df_dg_pks = df_dg.drop_duplicates().sort_values(['Kab/Kota','jns_kelamin'])

In [41]:
## Jumlah dokter gigi Rumah sakit

tables_page183 = camelot.read_pdf("2021.pdf", flavor='stream', pages='183')
df_page183 = tables_page183[0].df.iloc[37:, [1, 19, 21, 23, 25, 27, 29]]
df_page183 = df_page183.iloc[:-1]
df_page183.set_axis(['Kab/Kota', 'jml_dg_l', 'jml_dg_p', 'jml_dg_lp', 'jml_dgsp_l', 'jml_dgsp_p', 'jml_dgsp_lp'],
                    axis=1, inplace=True)
df_page183 = df_page183.replace('', '0')
df_page183 = df_page183.replace('-', '0')

# Convert numeric columns to integers
for col in df_page183.columns[~(df_page183.columns.str.contains('%') | (df_page183.columns == 'Kab/Kota'))]:
    df_page183[col] = df_page183[col].str.replace(',', '').astype(int)

# Read tables from page 184
tables_page184 = camelot.read_pdf("2021.pdf", flavor='stream', pages='184')
df_page184 = tables_page184[0].df.iloc[4:, [1, 18, 20, 22, 24, 26, 28]]
# df_page184 = df_page184.iloc[:-1]
df_page184.set_axis(['Kab/Kota', 'jml_dg_l', 'jml_dg_p', 'jml_dg_lp', 'jml_dgsp_l', 'jml_dgsp_p', 'jml_dgsp_lp'],
                    axis=1, inplace=True)
df_page184 = df_page184.replace('', '0')
df_page184 = df_page184.replace('-', '0')

# Convert numeric columns to integers
for col in df_page184.columns[~(df_page184.columns.str.contains('%') | (df_page184.columns == 'Kab/Kota'))]:
    df_page184[col] = df_page184[col].str.replace(',', '').astype(int)

# Combine the two DataFrames
df_combined = pd.concat([df_page183, df_page184], ignore_index=True)

df_combined

,Kab/Kota,jml_dg_l,jml_dg_p,jml_dg_lp,jml_dgsp_l,jml_dgsp_p,jml_dgsp_lp
0,Kabupaten Bogor,20,67,87,19,33,52
1,Kabupaten Sukabumi,8,19,27,7,1,8
2,Kabupaten Cianjur,15,51,66,1,2,3
3,Kabupaten Bandung,8,19,27,2,9,11
4,Kabupaten Garut,0,3,3,0,2,2
5,Kabupaten Tasikmalaya,1,2,3,0,0,0
6,Kabupaten Ciamis,2,6,8,0,2,2
7,Kabupaten Kuningan,7,12,19,0,1,1
8,Kabupaten Cirebon,3,17,20,7,8,15
9,Kabupaten Majalengka,1,5,6,1,0,1
10,Kabupaten Sumedang,2,2,4,1,0,1
11,Kabupaten Indramayu,3,11,14,1,4,5
12,Kabupaten Subang,5,6,11,1,0,1
13,Kabupaten Purwakarta,2,14,16,2,2,4
14,Kabupaten Karawang,15,31,46,7,8,15
15,Kabupaten Bekasi,27,100,127,12,30,42
16,Kabupaten Bandung Barat,5,10,15,3,1,4
17,Kabupaten Pangandaran,1,0,1,1,1,2
18,Kota Bogor,12,60,72,18,33,51
19,Kota Sukabumi,4,10,14,1,4,5
20,Kota Bandung,83,218,301,72,121,193
21,Kota Cirebon,6,14,20,9,7,16
22,Kota Bekasi,29,110,139,26,57,83
23,Kota Depok,21,63,84,29,64,93
24,Kota Cimahi,6,25,31,8,20,28
25,Kota Tasikmalaya,6,16,22,2,3,5
26,Kota Banjar,0,1,1,0,1,1

In [42]:
df_dg = pd.concat([
    df_combined.loc[:,['Kab/Kota','jml_dg_l']].rename(columns={'jml_dg_l':'jumlah'}).assign(jns_kelamin='laki-laki', profesi='dokter gigi', unit_kerja='rumah sakit'),
    df_combined.loc[:,['Kab/Kota','jml_dg_p']].rename(columns={'jml_dg_p':'jumlah'}).assign(jns_kelamin='perempuan', profesi='dokter gigi', unit_kerja='rumah sakit'),
    df_combined.loc[:,['Kab/Kota','jml_dgsp_l']].rename(columns={'jml_dgsp_l':'jumlah'}).assign(jns_kelamin='laki-laki', profesi='dokter gigi spesialis', unit_kerja='rumah sakit'),
    df_combined.loc[:,['Kab/Kota','jml_dgsp_p']].rename(columns={'jml_dgsp_p':'jumlah'}).assign(jns_kelamin='perempuan', profesi='dokter gigi spesialis', unit_kerja='rumah sakit')
], ignore_index=True)

# Menghapus duplikat dan mengurutkan data berdasarkan 'Kab/Kota' dan 'jns_kelamin'
df_dg_rs = df_dg.drop_duplicates().sort_values(['Kab/Kota','jns_kelamin'])

In [45]:
## Klinik DIKLAT KESEHATAN
df_garut = pd.DataFrame({
    'Kab/Kota': ['Kabupaten Garut'],
    'jml_dg_l': [4],
    'jml_dg_p': [7],
    'jml_dgsp_l': [1],
    'jml_dgsp_p': [0]
})

df_bekasi = pd.DataFrame({
    'Kab/Kota': ['Kabupaten Bekasi'],
    'jml_dg_l': [31],
    'jml_dg_p': [139],
    'jml_dgsp_l': [11],
    'jml_dgsp_p': [28]
})

df_combined = pd.concat([df_garut, df_bekasi], ignore_index=True)

df_dg = pd.concat([
    df_combined.loc[:,['Kab/Kota','jml_dg_l']].rename(columns={'jml_dg_l':'jumlah'}).assign(jns_kelamin='laki-laki', profesi='dokter gigi', unit_kerja='klinik diklat kesehatan'),
    df_combined.loc[:,['Kab/Kota','jml_dg_p']].rename(columns={'jml_dg_p':'jumlah'}).assign(jns_kelamin='perempuan', profesi='dokter gigi', unit_kerja='klinik diklat kesehatan'),
    df_combined.loc[:,['Kab/Kota','jml_dgsp_l']].rename(columns={'jml_dgsp_l':'jumlah'}).assign(jns_kelamin='laki-laki', profesi='dokter gigi spesialis', unit_kerja='klinik diklat kesehatan'),
    df_combined.loc[:,['Kab/Kota','jml_dgsp_p']].rename(columns={'jml_dgsp_p':'jumlah'}).assign(jns_kelamin='perempuan', profesi='dokter gigi spesialis', unit_kerja='klinik diklat kesehatan')
], ignore_index=True)

# Menghapus duplikat dan mengurutkan data berdasarkan 'Kab/Kota' dan 'jns_kelamin'
df_dg_dikkes = df_dg.drop_duplicates().sort_values(['Kab/Kota','jns_kelamin'])

In [46]:
## Klinik Dinas Kesehatan
data_garut = {'Kab/Kota': 'Kabupaten Garut',
              'jml_dg_l': 1,
              'jml_dg_p': 1,
              'jml_dgsp_l': 0,
              'jml_dgsp_p': 0}

data_bandung = {'Kab/Kota': 'Kota Bandung',
                'jml_dg_l': 34,
                'jml_dg_p': 119,
                'jml_dgsp_l': 10,
                'jml_dgsp_p': 23}

data_cirebon = {'Kab/Kota': 'Kota Cirebon',
                 'jml_dg_l': 4,
                 'jml_dg_p': 16,
                 'jml_dgsp_l': 0,
                 'jml_dgsp_p': 0}

data_tasikmalaya = {'Kab/Kota': 'Kota Tasikmalaya',
                    'jml_dg_l': 24,
                    'jml_dg_p': 44,
                    'jml_dgsp_l': 18,
                    'jml_dgsp_p': 20}

df_garut = pd.DataFrame([data_garut])
df_bandung = pd.DataFrame([data_bandung])
df_cirebon = pd.DataFrame([data_cirebon])
df_tasikmalaya = pd.DataFrame([data_tasikmalaya])

df_combined = pd.concat([df_garut, df_bandung, df_cirebon, df_tasikmalaya], ignore_index=True)

df_dg = pd.concat([
    df_combined.loc[:,['Kab/Kota','jml_dg_l']].rename(columns={'jml_dg_l':'jumlah'}).assign(jns_kelamin='laki-laki', profesi='dokter gigi', unit_kerja='klinik DINKES'),
    df_combined.loc[:,['Kab/Kota','jml_dg_p']].rename(columns={'jml_dg_p':'jumlah'}).assign(jns_kelamin='perempuan', profesi='dokter gigi', unit_kerja='klinik DINKES'),
    df_combined.loc[:,['Kab/Kota','jml_dgsp_l']].rename(columns={'jml_dgsp_l':'jumlah'}).assign(jns_kelamin='laki-laki', profesi='dokter gigi spesialis', unit_kerja='klinik DINKES'),
    df_combined.loc[:,['Kab/Kota','jml_dgsp_p']].rename(columns={'jml_dgsp_p':'jumlah'}).assign(jns_kelamin='perempuan', profesi='dokter gigi spesialis', unit_kerja='klinik DINKES')
], ignore_index=True)

# Menghapus duplikat dan mengurutkan data berdasarkan 'Kab/Kota' dan 'jns_kelamin'
df_dg_dinkes = df_dg.drop_duplicates().sort_values(['Kab/Kota','jns_kelamin'])
df_dg = pd.concat([df_dg_pks,df_dg_rs,df_dg_dikkes,df_dg_dinkes], ignore_index=True)
tahun = "2021"
df_dg['tahun'] = tahun
df_dg.to_csv(f'dataset/dg_unit_kerja/{tahun}.csv', index=False)
df_dg

,Kab/Kota,jumlah,jns_kelamin,profesi,unit_kerja,tahun
0,Kabupaten Bandung,11,laki-laki,dokter gigi,puskesmas,2021
1,Kabupaten Bandung,0,laki-laki,dokter gigi spesialis,puskesmas,2021
2,Kabupaten Bandung,62,perempuan,dokter gigi,puskesmas,2021
3,Kabupaten Bandung,0,perempuan,dokter gigi spesialis,puskesmas,2021
4,Kabupaten Bandung Barat,7,laki-laki,dokter gigi,puskesmas,2021
...,...,...,...,...,...,...
235,Kota Cirebon,0,perempuan,dokter gigi spesialis,klinik DINKES,2021
236,Kota Tasikmalaya,24,laki-laki,dokter gigi,klinik DINKES,2021
237,Kota Tasikmalaya,18,laki-laki,dokter gigi spesialis,klinik DINKES,2021
238,Kota Tasikmalaya,44,perempuan,dokter gigi,klinik DINKES,2021
239,Kota Tasikmalaya,20,perempuan,dokter gigi spesialis,klinik DINKES,2021

In [15]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 9 to 35
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Kab/Kota     27 non-null     object
 1   jml_dg_l     27 non-null     int32
 2   jml_dg_p     27 non-null     int32
 3   jml_dg_lp    27 non-null     int32
 4   jml_dgsp_l   27 non-null     int32
 5   jml_dgsp_p   27 non-null     int32
 6   jml_dgsp_lp  27 non-null     int32
dtypes: int32(6), object(1)
memory usage: 996.0+ bytes
None

In [3]:
pd.options.display.max_columns = None

# Data Tahap 1

In [5]:
def check_for_jabatan(page):
    '''
    Fungsi untuk mengecek keberadaan informasi jurusan pilihan
    Input: page (ex: pdf.pages[0])
    Output: 
        - dicitionary berisi informasi jurusan pilihan
    '''
    if "Jumlah Tenaga Kesehatan di Puskesmas" in page.extract_text():
        text = pg.extract_text()
        pendidikan = pg.extract_tables()[1][0][1]
        jurusan_strings = text.split("Jurusan : ")[1].split("Lokasi")[0]
        lokasi_front = ""
        jurusan = jurusan_strings.split("\n")[0]

        lokasi_string = text.split("Lokasi Formasi : ")[1].split("Jenis")[0]

        return {
            "kode_jurusan": jurusan.split(" - ")[0],
            "jurusan": jurusan.split(" - ")[1],
            "kode_lokasi": lokasi_string.split(" - ")[0],
            "lokasi_formasi": lokasi_string.split(" - ")[1].split("\n")[0],
            "pendidikan": pendidikan.replace("\n", " ")
        }
    else:
        return {}

def check_for_detail_tables(page):
    '''
    Fungsi untuk mengecek keberadaan tabel perorangan
    Input: page (ex: pdf.pages[0])
    Output: 
        - found (binary, iya tidaknya sebuah halaman punya tabel perorangan)
        - df_returned (tabel perorangan jika ada)
    '''
    found = False
    df_returned = pd.DataFrame()
    for table in pg.extract_tables():
        df = pd.DataFrame(table)

        if (df.shape[1] == 9): #jumlah kolom = 9 
            found = True
            df_returned = df
    return found, df_returned


def split_df(df_):
    '''
    Fungsi untuk split tabel perorangan. Kadang ada satu halaman dengan lebih dari satu tabel.
    Input: df_ (dataframe tabel perorangan)
    Output: 
        - list berisi beberapa dataframe untuk tiap individu
    '''
    dfs = []
    header_indexes = list(df_[df_[1]=="No Peserta"].index)
    header_indexes.append(len(df_))
    for i in range(len(header_indexes)-1):
        splitted_df = df_.iloc[header_indexes[i]: header_indexes[i+1], :]
        splitted_df.index = range(len(splitted_df))
        dfs.append(splitted_df)
    return dfs

def get_info_from_table(df_, idx):
    '''
    Fungsi untuk mengekstrak informasi dari tabel perorangan 
    Input: df_ (dataframe tabel perorangan)
    Output: 
        - dicitionary berisi informasi perorangan yang telah diekstrak
    '''
    base_data =  {
        "no_peserta": df_.iloc[idx,1],
        "kode_pendidikan": df_.iloc[idx,2],
        "total_twk": df_.iloc[idx,4],
        "total_tiu": df_.iloc[idx,5],
        "total_tkp": df_.iloc[idx,6],
        "total_skd": df_.iloc[idx,7],
        "keterangan": df_.iloc[idx,8]
    }

    return {**base_data}

In [7]:
start_index = 0
end_index = 929
pdf = pdfplumber.open('datasets/Lampiran B-099.02720.06.2022 Pengumuman Hasil Tahap 1 Tahun 2022.pdf')

# start iterating
result = []
last_jabatan = {}

start_time = dt.datetime.now()
start_time = dt.datetime.now()
for i in range(start_index, end_index):
    pg = pdf.pages[i]

    # jika halaman tsb ada info tentang lowongan, simpan
    current_jabatan = check_for_jabatan(pg)
    if current_jabatan != {}:
        last_jabatan = current_jabatan
    
    is_detail_found, detail_df = check_for_detail_tables(pg)
    # jika ketemu ada tabel perorangan
    if is_detail_found:
        splitted_df = split_df(detail_df)
        for df_ in splitted_df:
            for i in range(2, len(df_)):
                details = get_info_from_table(df_, i)
                if current_jabatan == {}:
                    # kalo ada info lowongan di halaman yang sama, pakai info lowongan tsb
                    details.update(last_jabatan)
                else:
                    # kalo ga, pake info lowongan terakhir
                    details.update(current_jabatan)
                    last_jabatan = current_jabatan
                result.append(details)

    # untuk logging
    if i%100 == 99:
        curr_time = dt.datetime.now()
        print("Done for "+str(i), curr_time-start_time)
        start_time = dt.datetime.now()

res = pd.DataFrame(result)

OSError: [Errno 22] Invalid argument: 'spmb_0_929_2024-02-18 13:35:49.467388.csv'

In [9]:
res.to_csv('Tahap 1.csv')