Data diambil dari bps dalam topik profil ketenagakerjaan tahun 2022 setiap kab/kota yang dianalisa lebih dalam

In [6]:
# import library
import tabula
import camelot
import pandas as pd
import datetime as dt
import sys
from scipy.spatial import distance
from pathlib import Path

pd.options.display.max_columns = None

In [2]:
df = pd.read_csv("dataset/dataset_analisa_tambahan/bps-od_17106_jml_pengeluaran_per_kapita__kabupatenkota_data.csv")
df.head()

,id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_pengeluaran_per_kapita,satuan,tahun
0,268,32,JAWA BARAT,3201,KABUPATEN BOGOR,10317.0,RIBU RUPIAH,2020
1,269,32,JAWA BARAT,3202,KABUPATEN SUKABUMI,8823.0,RIBU RUPIAH,2020
2,270,32,JAWA BARAT,3203,KABUPATEN CIANJUR,7980.0,RIBU RUPIAH,2020
3,271,32,JAWA BARAT,3204,KABUPATEN BANDUNG,10201.0,RIBU RUPIAH,2020
4,272,32,JAWA BARAT,3205,KABUPATEN GARUT,7876.0,RIBU RUPIAH,2020

In [3]:
df = df[['nama_kabupaten_kota', 'jumlah_pengeluaran_per_kapita', 'tahun']]
df['tahun'] = df['tahun'].astype('str')
df['jumlah_pengeluaran_per_kapita'] = df['jumlah_pengeluaran_per_kapita'].astype('int')
df['nama_kabupaten_kota'] = df['nama_kabupaten_kota'].str.title()
df.to_csv("dataset/dataset_clean/pengeluaran_perkapita_kab.csv", index=False)
df.head()

  nama_kabupaten_kota  jumlah_pengeluaran_per_kapita tahun
0     Kabupaten Bogor                          10317  2020
1  Kabupaten Sukabumi                           8823  2020
2   Kabupaten Cianjur                           7980  2020
3   Kabupaten Bandung                          10201  2020
4     Kabupaten Garut                           7876  2020

In [13]:
df1 = pd.DataFrame({
    'Status Pekerjaan Utama': ['Berusaha Sendiri', 'Berusaha dibantu buruh tidak tetap/buruh tidak dibayar', 
                               'Berusaha dibantu buruh tetap/buruh dibayar', 
                               'Buruh/Karyawan/Pegawai', 
                               'Pekerja Bebas', 
                               'Pekerja keluarga/tidak dibayar'],
    'Total': [197371, 70986, 17903, 291364, 119814, 43201],
    'Kabupaten/Kota': ['Kabupaten Bandung Barat'] * 6,
    'Status': "Need Attention"
})

df2 = pd.DataFrame({
    'Status Pekerjaan Utama': ['Berusaha Sendiri', 
                               'Berusaha dibantu buruh tidak tetap/buruh tidak dibayar', 
                               'Berusaha dibantu buruh tetap/buruh dibayar', 
                               'Buruh/karyawan/pegawai', 
                               'Pekerja bebas di pertanian', 
                               'Pekerja bebas di nonpertanian', 
                               'Pekerja keluarga/tidak dibayar'],
    'Total': [126182, 64840, 17073, 142984, 31343, 45361, 50967],
    'Kabupaten/Kota': ['Kabupaten Kuningan'] * 7,
    'Status': "Need Attention"
})

df3 = pd.DataFrame({
    'Status Pekerjaan Utama': ['Berusaha Sendiri', 'Berusaha dibantu buruh tidak tetap/buruh tidak dibayar', 'Berusaha dibantu buruh tetap/buruh dibayar', 'Buruh/karyawan/pegawai', 'Pekerja bebas di pertanian', 'Pekerja bebas di nonpertanian', 'Pekerja keluarga/tidak dibayar'],
    'Total': [300758, 216361, 44208, 257147, 107970, 140180, 162594],
    'Kabupaten/Kota': ['Kabupaten Garut'] * 7,
    'Status': "Benchmark"
})

df4 = pd.DataFrame({
    'Status Pekerjaan Utama': ['Berusaha sendiri', 'Berusaha dibantu buruh tidak tetap/buruh tidak dibayar', 'Berusaha dibantu buruh tetap/buruh dibayar', 'Buruh/Karyawan/Pegawai', 'Pekerja bebas', 'Pekerja keluarga/tidak dibayar'],
    'Total': [62962, 16473, 10818, 163287, 10501, 18357],
    'Kabupaten/Kota': ['Kota Cimahi'] * 6,
    'Status': "Need Attention"
})

df5 = pd.DataFrame({
    'Status Pekerjaan Utama': ['Berusaha sendiri', 'Berusaha dibantu buruh tidak tetap/buruh tidak dibayar', 'Berusaha dibantu buruh tetap/buruh dibayar', 'Buruh/Karyawan/Pegawai', 'Pekerja bebas', 'Pekerja keluarga/tidak dibayar'],
    'Total': [44891, 9862, 9895, 72464, 11186, 8464],
    'Kabupaten/Kota': ['Kota Sukabumi'] * 6,
    'Status': "Need Attention"
})

df6 = pd.DataFrame({
    'Status Pekerjaan Utama': ['Berusaha sendiri', 'Berusaha dibantu buruh tidak tetap/buruh tidak dibayar', 'Berusaha dibantu buruh tetap/buruh dibayar', 'Buruh/Karyawan/Pegawai', 'Pekerja bebas', 'Pekerja keluarga/tidak dibayar'],
    'Total': [41774, 70819, 10924, 49544, 35602, 48021],
    'Kabupaten/Kota': ['Kabupaten Pangandaran'] * 6,
    'Status': "Need Attention"
})

df7 = pd.DataFrame({
    'Status Pekerjaan Utama': ['Berusaha Sendiri', 'Berusaha dibantu buruh tidak tetap/buruh tidak dibayar', 'Berusaha dibantu buruh tetap/dibayar', 'Buruh/karyawan/pegawai', 'Pekerja bebas di pertanian & non pertanian', 'Pekerja keluarga/tidak dibayar'],
    'Total': [300049, 59114, 56563, 679688, 35272, 71799],
    'Kabupaten/Kota': ['Kota Bandung'] * 6,
    'Status': "Benchmark"
})

df8 = pd.DataFrame({
    'Status Pekerjaan Utama': ['Berusaha sendiri', 'Berusaha dibantu buruh tidak tetap/buruh tidak dibayar', 'Berusaha dibantu buruh tetap/buruh dibayar', 'Buruh/Karyawan/Pegawai', 'Pekerja bebas', 'Pekerja keluarga/tidak dibayar'],
    'Total': [234976, 52434, 33283, 744503, 41390, 53727],
    'Kabupaten/Kota': ['Kota Depok'] * 6,
    'Status': "Need Attention"
})
df9 = pd.DataFrame({
    'Status Pekerjaan Utama': ['Berusaha sendiri', 'Berusaha dibantu buruh tidak tetap/buruh tidak dibayar', 'Berusaha dibantu buruh tetap/buruh dibayar', 'Buruh/Karyawan/Pegawai/Employee', 'Pekerja bebas', 'Pekerja keluarga/tak dibayar'],    
    'Total': [221748, 141936, 22105, 205749, 208760, 101169],
    'Kabupaten/Kota': ['Kabupaten Tasikmalaya'] * 6,
    'Status': "Benchmark"
})

df10 = pd.DataFrame({
    'Status Pekerjaan Utama': ['Berusaha sendiri', 'Berusaha dibantu buruh tidak tetap/buruh tidak dibayar', 'Berusaha dibantu buruh tetap/buruh dibayar', 'Buruh/Karyawan/Pegawai/Employee', 'Pekerja bebas di pertanian', 'Pekerja bebas di non pertanian', 'Pekerja keluarga/tak dibayar Family worker/unpaid worker'],
    'Total': [195671, 177544, 52024, 267239, 125288, 101801, 146756],
    'Kabupaten/Kota': ['Kabupaten Cianjur'] * 7,
    'Status': "Benchmark"
})

# Menggabungkan semua DataFrame
df_combined = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9,df10], ignore_index=True)
df_top3 = df_combined.groupby('Kabupaten/Kota').apply(lambda x: x.nlargest(3, 'Total')).reset_index(drop=True)

df_top3.to_csv("dataset/dataset_clean/jenis_pekerjaan_kab.csv", index=False)
df_top3.head()

PermissionError: [Errno 13] Permission denied: 'dataset/dataset_clean/jenis_pekerjaan_kab.csv'

In [14]:
data = {'x1': [26, 24, 24, 28, 28, 24, 52, 37, 47, 33],
        'y1': [1354, 205, 714, 404, 123, 121, 776, 523, 758, 105],
        'Kabupaten/Kota': ['Kabupaten Bandung Barat', 'Kabupaten Cianjur', 'Kabupaten Garut', 'Kabupaten Kuningan', 'Kabupaten Pangandaran', 'Kabupaten Tasikmalaya', 'Kota Bandung', 'Kota Cimahi', 'Kota Depok', 'Kota Sukabumi'],
        'Status': ['Need Attention', 'Benchmark', 'Benchmark', 'Need Attention', 'Need Attention', 'Benchmark', 'Need Attention', 'Need Attention', 'Need Attention', 'Need Attention']}
df = pd.DataFrame(data)

# Filter dataframe for cities with status "Need Attention" and "Benchmark"
need_attention = df[df['Status'] == 'Need Attention']
benchmark = df[df['Status'] == 'Benchmark']

# Calculate distance between cities
XA = need_attention[['x1', 'y1']].values
XB = benchmark[['x1', 'y1']].values
distances = distance.cdist(XA, XB, 'euclidean')

# Find closest benchmark city for each city with status "Need Attention"
closest_benchmark = distances.argmin(axis=1)
closest_benchmark_names = benchmark['Kabupaten/Kota'].iloc[closest_benchmark].tolist()

# Add new column to dataframe
need_attention['Closest Benchmark'] = closest_benchmark_names
need_attention.to_csv("dataset/dataset_clean/benchmark_metode.csv", index=False)
need_attention.head()

<ipython-input-14-50befe936968>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  need_attention['Closest Benchmark'] = closest_benchmark_names

   x1    y1           Kabupaten/Kota          Status      Closest Benchmark
0  26  1354  Kabupaten Bandung Barat  Need Attention        Kabupaten Garut
3  28   404       Kabupaten Kuningan  Need Attention      Kabupaten Cianjur
4  28   123    Kabupaten Pangandaran  Need Attention  Kabupaten Tasikmalaya
6  52   776             Kota Bandung  Need Attention        Kabupaten Garut
7  37   523              Kota Cimahi  Need Attention        Kabupaten Garut