# Install Library yang diperlukan

Ini adalah script untuk mengubah pdf lampiran hasil CPNS jadi csv
Caveat: kalo langsung prosess 20rb halaman, agak keselek di tengah, jadi mending di-iterate beberapa halaman
Saya yakin ada cara yang lebih elegan. Feel free to give me any suggestions

Cara run </br>
python export_data_to_csv.py index_halaman_start index_halaman_end

Misal </br>
python export_data_to_csv.py 0 100

In [1]:
# import library
import tabula
import camelot
import pandas as pd
import datetime as dt
import sys

pd.options.display.max_columns = None

## Scraping Data

In [10]:
# Tenaga Puskemas

# Replace "nama_file.pdf" with your actual file path
tables = camelot.read_pdf("2019.pdf", flavor='stream', pages='41')
df = tables[1].df
df = df.iloc[4:,:2]
df = df.iloc[:9]
df.set_axis(["Jenis Tenaga Kesehatan", "Jumlah Tenaga Kesehatan"], axis=1, inplace=True)
df.rename(columns={'Jenis Tenaga Kesehatan': "Jenis Tenaga", "Jumlah Tenaga Kesehatan" : "Jumlah Tenaga"}, inplace = True)
df['Jumlah Tenaga'] = df['Jumlah Tenaga'].astype(str)
df['Jumlah Tenaga'] = df['Jumlah Tenaga'].str.replace(",", "")

df['Jumlah Tenaga'] = df['Jumlah Tenaga'].astype(int)
df['tahun'] = "2019"
df['unit_kerja'] = "puskesmas"
df

C:\Users\ACER\anaconda3\lib\site-packages\camelot\parsers\stream.py:365: UserWarning: No tables found in table area 1
  warnings.warn(f"No tables found in table area {table_idx + 1}")

                         Jenis Tenaga  Jumlah Tenaga tahun unit_kerja
4   Dokter atau dokter layanan primer           2401  2019  puskesmas
5                         Dokter gigi            860  2019  puskesmas
6                             Perawat          10104  2019  puskesmas
7                               Bidan          14687  2019  puskesmas
8                  Tenaga kefarmasian           1352  2019  puskesmas
9                       Tenaga Kesmas           1491  2019  puskesmas
10        Tenaga kesehatan Lingkungan            862  2019  puskesmas
11                        Tenaga gizi            962  2019  puskesmas
12  Ahli Teknologi Laboratorium Medik            811  2019  puskesmas

In [17]:
# Tenaga Rumah Sakit

tables = camelot.read_pdf("2019.pdf", flavor='stream', pages='45')
df = tables[1].df
df = df.iloc[2:,: ]
df = df.iloc[:-1,: ]
df.set_axis(["Jenis Tenaga Kesehatan", "Jumlah Tenaga Kesehatan"], axis=1, inplace=True)
df.rename(columns={'Jenis Tenaga Kesehatan': "Jenis Tenaga", "Jumlah Tenaga Kesehatan" : "Jumlah Tenaga"}, inplace = True)
df['Jumlah Tenaga'] = df['Jumlah Tenaga'].astype(str)
df['Jumlah Tenaga'] = df['Jumlah Tenaga'].str.replace(".", "")

df['Jumlah Tenaga'] = df['Jumlah Tenaga'].astype(int)
df['tahun'] = "2019"
df['unit_kerja'] = "rumah sakit"
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 2 to 11
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Jenis Tenaga   10 non-null     object
 1   Jumlah Tenaga  10 non-null     int32
 2   tahun          10 non-null     object
 3   unit_kerja     10 non-null     object
dtypes: int32(1), object(3)
memory usage: 412.0+ bytes

<ipython-input-17-28cc7147675c>:10: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Jumlah Tenaga'] = df['Jumlah Tenaga'].str.replace(".", "")

In [21]:
## Rekapitulasi Rasio Tenaga Kesehatan /100.000

df = tabula.read_pdf("2019.pdf", pages="46")[0]

df.set_axis(["jenis_tenaga","Ratio/100.000 Penduduk"], axis=1, inplace=True)

df['tahun'] = "2019"
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   jenis_tenaga            12 non-null     object
 1   Ratio/100.000 Penduduk  12 non-null     float64
 2   tahun                   12 non-null     object
dtypes: float64(1), object(2)
memory usage: 416.0+ bytes

In [26]:
## Jumlah Fasilitas Kesehatan Menurut Kepemilikan 
### Data ini dicek secara manual pada setiap laporan kesehatan per kab/kota 2022

tables = camelot.read_pdf("2019.pdf", flavor='stream', pages='139')

df = tables[0].df

df = df.iloc[11:,[1,27] ]

df.set_axis(["Kabupaten/Kota", "Jumlah"], axis=1, inplace=True)
df.reset_index(drop=True, inplace=True)

df['Jumlah'] = df['Jumlah'].str.replace("-", "0")
df['Jumlah'] = df['Jumlah'].replace('', '0')
df['Jumlah'] = df['Jumlah'].str.replace(".", "")
df['Jumlah'] = pd.to_numeric(df['Jumlah'], errors='coerce').fillna(0).astype(int)
df['tahun'] = "2019"
df

<ipython-input-26-b35c5dcfa198>:15: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Jumlah'] = df['Jumlah'].str.replace(".", "")

             Kabupaten/Kota  Jumlah tahun
0           Kabupaten Bogor     171  2019
1        Kabupaten Sukabumi      40  2019
2         Kabupaten Cianjur       0  2019
3         Kabupaten Bandung       0  2019
4           Kabupaten Garut      18  2019
5     Kabupaten Tasikmalaya      10  2019
6          Kabupaten Ciamis       0  2019
7        Kabupaten Kuningan       0  2019
8         Kabupaten Cirebon      71  2019
9      Kabupaten Majalengka      25  2019
10       Kabupaten Sumedang       0  2019
11      Kabupaten Indramayu       0  2019
12         Kabupaten Subang       0  2019
13     Kabupaten Purwakarta       0  2019
14       Kabupaten Karawang      25  2019
15         Kabupaten Bekasi      43  2019
16  Kabupaten Bandung Barat       0  2019
17    Kabupaten Pangandaran       0  2019
18               Kota Bogor      57  2019
19            Kota Sukabumi       0  2019
20             Kota Bandung       0  2019
21             Kota Cirebon       0  2019
22              Kota Bekasi       0  2019
23               Kota Depok       0  2019
24              Kota Cimahi      53  2019
25         Kota Tasikmalaya       0  2019
26              Kota Banjar       0  2019
27               JAWA BARAT     513  2019

In [50]:
### PELAYANAN KESEHATAN GIGI DAN MULUT MENURUT KECAMATAN DAN PUSKESMAS

tables = camelot.read_pdf("2019.pdf", flavor='stream', pages='203')

df = tables[0].df

df = df.iloc[6:,[1,3] + list(range(5, df.shape[1])) ]
df.reset_index(drop=True, inplace=True)
df.iloc[22,4] = "163839"
df.iloc[22,6] = "0,04"
df.iloc[27,0] = "Jawa Barat"
df.set_axis(["Kabupaten/Kota", "Jumlah Tumpatan Gigi Tetap", "Pencabutan Gigi Tetap", "Rasio Pencabutan", "Jumlah Kasus Gigi", "Jumlah Kasus dirujuk", "% Rasio Dirujuk"], axis=1, inplace=True)
df = df.replace('', '0')
df = df.replace('-', '0')
df = df.replace('#DIV/0!', '0')
for col in ['Rasio Pencabutan', '% Rasio Dirujuk']:
    df[col] = df[col].str.replace(',', '.').astype(float)

for col in ['Jumlah Tumpatan Gigi Tetap', 'Pencabutan Gigi Tetap', 'Jumlah Kasus Gigi', 'Jumlah Kasus dirujuk']:
    df[col] = df[col].str.replace('.', '').astype(int)
df['tahun'] = "2019"
df['unit_kerja'] = "puskesmas"
df

<ipython-input-50-701d99f7d70c>:20: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df[col] = df[col].str.replace('.', '').astype(int)

,Kabupaten/Kota,Jumlah Tumpatan Gigi Tetap,Pencabutan Gigi Tetap,Rasio Pencabutan,Jumlah Kasus Gigi,Jumlah Kasus dirujuk,% Rasio Dirujuk,tahun,unit_kerja
0,Kabupaten Bogor,17256,24099,0.7,353282,3885,1.10,2019,puskesmas
1,Kabupaten Sukabumi,0,0,0.0,0,0,0.00,2019,puskesmas
2,Kabupaten Cianjur,0,0,0.0,0,0,0.00,2019,puskesmas
3,Kabupaten Bandung,32115,28534,1.1,312343,4319,1.40,2019,puskesmas
4,Kabupaten Garut,0,0,0.0,0,0,0.00,2019,puskesmas
5,Kabupaten Tasikmalaya,2280,6084,0.4,26535,1151,4.30,2019,puskesmas
6,Kabupaten Ciamis,599,402,1.5,0,0,0.00,2019,puskesmas
7,Kabupaten Kuningan,2481,4075,0.6,29457,3711,12.60,2019,puskesmas
8,Kabupaten Cirebon,29710,41812,0.7,60844,18274,30.00,2019,puskesmas
9,Kabupaten Majalengka,1664,5751,0.3,61167,4005,6.50,2019,puskesmas
10,Kabupaten Sumedang,0,0,0.0,0,0,0.00,2019,puskesmas
11,Kabupaten Indramayu,11193,628,17.8,0,0,0.00,2019,puskesmas
12,Kabupaten Subang,5749,6033,1.0,5715,277,4.80,2019,puskesmas
13,Kabupaten Purwakarta,2155,2342,0.9,34143,3793,11.10,2019,puskesmas
14,Kabupaten Karawang,3933,7386,0.5,72118,1404,1.90,2019,puskesmas
15,Kabupaten Bekasi,9891,6974,1.4,55476,4425,8.00,2019,puskesmas
16,Kabupaten Bandung Barat,0,0,0.0,0,0,0.00,2019,puskesmas
17,Kabupaten Pangandaran,0,0,0.0,0,0,0.00,2019,puskesmas
18,Kota Bogor,13508,5481,2.5,111832,4269,3.80,2019,puskesmas
19,Kota Sukabumi,0,0,0.0,0,0,0.00,2019,puskesmas
20,Kota Bandung,32566,20188,1.6,250491,18810,7.50,2019,puskesmas
21,Kota Cirebon,0,0,0.0,0,0,0.00,2019,puskesmas
22,Kota Bekasi,11331,117,96.8,163839,6194,0.04,2019,puskesmas
23,Kota Depok,30466,5996,5.1,86252,4610,5.30,2019,puskesmas
24,Kota Cimahi,5617,2689,2.1,50447,3011,6.00,2019,puskesmas
25,Kota Tasikmalaya,0,0,0.0,0,0,0.00,2019,puskesmas
26,Kota Banjar,260,881,0.3,10872,534,4.90,2019,puskesmas
27,Jawa Barat,212774,169472,1.3,1521181,82672,5.40,2019,puskesmas

In [55]:
## PELAYANAN KESEHATAN GIGI DAN MULUT PADA ANAK SD DAN SETINGKAT MENURUT JENIS KELAMIN, KECAMATAN, DAN PUSKESMAS

tables = camelot.read_pdf("2019.pdf", flavor='stream', pages='204')

df = tables[0].df

columns_to_drop = [12,15,18]
df = df.iloc[4:, [1, 2] + list(range(4, df.shape[1]))].drop(columns=columns_to_drop)

df.reset_index(drop=True, inplace=True)
df.iloc[27,0] = "Jawa Barat"
df.iloc[9,15] = "89.9"
df.set_axis(['Kabupaten/Kota', 'jumlah_SD/MI','jumlah_SD/MI_SG_Massal','%jumlah_SD/MI_SG_Massal',
             'jumlah_SD/MI_LG','%jumlah_SD/MI_LG',
            'jumlah_murid_SD/MI_L', 'jumlah_murid_SD/MI_P', 'jumlah_murid_SD/MI_LP',
            'jumlah_murid_SD/MI_L_Diperiksa','%jumlah_murid_SD/MI_L_Diperiksa','jumlah_murid_SD/MI_P_Diperiksa','%jumlah_murid_SD/MI_P_Diperiksa', 'jumlah_murid_SD/MI_LP_Diperiksa','%jumlah_murid_SD/MI_LP_Diperiksa',
            'jumlah_murid_SD/MI_L_PR','jumlah_murid_SD/MI_P_PR','jumlah_murid_SD/MI_LP_PR',
            'jumlah_murid_SD/MI_L_MP','%jumlah_murid_SD/MI_L_MP','jumlah_murid_SD/MI_P_MP','%jumlah_murid_SD/MI_P_MP','jumlah_murid_SD/MI_LP_MP','%jumlah_murid_SD/MI_LP_MP'], axis=1, inplace=True)
df = df.replace('', '0')
df = df.replace('-', '0')

## Replace #DIV N #Value
for col in df.columns:
    df.loc[df[col].astype(str).str.contains('#'), col] = 0

for col in df.columns[df.columns.str.contains('%')]:
    df[col] = df[col].str.replace(',', '.').astype(float)

for col in df.columns[~(df.columns.str.contains('%') | (df.columns == 'Kabupaten/Kota'))]:
    df[col] = df[col].replace('\.', '', regex=True).astype(int)
df.fillna(0, inplace=True)

df['tahun'] = "2019"
df['unit_kerja'] = "puskesmas"
df

,Kabupaten/Kota,jumlah_SD/MI,jumlah_SD/MI_SG_Massal,%jumlah_SD/MI_SG_Massal,jumlah_SD/MI_LG,%jumlah_SD/MI_LG,jumlah_murid_SD/MI_L,jumlah_murid_SD/MI_P,jumlah_murid_SD/MI_LP,jumlah_murid_SD/MI_L_Diperiksa,%jumlah_murid_SD/MI_L_Diperiksa,jumlah_murid_SD/MI_P_Diperiksa,%jumlah_murid_SD/MI_P_Diperiksa,jumlah_murid_SD/MI_LP_Diperiksa,%jumlah_murid_SD/MI_LP_Diperiksa,jumlah_murid_SD/MI_L_PR,jumlah_murid_SD/MI_P_PR,jumlah_murid_SD/MI_LP_PR,jumlah_murid_SD/MI_L_MP,%jumlah_murid_SD/MI_L_MP,jumlah_murid_SD/MI_P_MP,%jumlah_murid_SD/MI_P_MP,jumlah_murid_SD/MI_LP_MP,%jumlah_murid_SD/MI_LP_MP,tahun,unit_kerja
0,Kabupaten Bogor,1954,1954,100.0,1699,86.9,115976,133161,249137,17540,15.0,17640,13.2,35180,14.1,3963,3796,7759,3963,100.0,3796,100.0,7759,100.0,2019,puskesmas
1,Kabupaten Sukabumi,1525,293,19.2,240,15.7,0,0,131176,0,0.0,0,0.0,22849,17.4,0,0,280,0,0.0,0,0.0,50,17.9,2019,puskesmas
2,Kabupaten Cianjur,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,2019,puskesmas
3,Kabupaten Bandung,1726,950,55.0,1567,90.8,222417,151055,373472,181148,81.4,120518,79.8,301666,80.8,46268,49179,95447,15085,32.6,16241,33.0,31326,32.8,2019,puskesmas
4,Kabupaten Garut,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,2019,puskesmas
5,Kabupaten Tasikmalaya,6468,3323,51.4,8624,133.3,4228,5011,9239,32096,759.1,31293,624.5,63389,0.0,9192,9556,18748,3206,34.9,3577,37.4,6783,36.2,2019,puskesmas
6,Kabupaten Ciamis,882,882,100.0,882,100.0,20027,18741,38768,9679,48.3,8945,47.7,18624,48.0,4947,3770,8717,2828,57.2,2536,67.3,5364,61.5,2019,puskesmas
7,Kabupaten Kuningan,697,330,47.3,557,79.9,48260,44887,93147,30652,63.5,28617,63.8,59269,63.6,9327,9121,18448,5791,62.1,5787,63.4,11578,62.8,2019,puskesmas
8,Kabupaten Cirebon,1060,345,32.5,1060,100.0,0,0,0,67116,0.0,67884,0.0,135000,0.0,19309,19496,38805,8049,41.7,8718,44.7,16767,43.2,2019,puskesmas
9,Kabupaten Majalengka,713,574,80.5,713,67.3,0,0,116,0,0.0,0,0.0,52662,0.0,899,0,14810,0,0.0,0,0.0,10277,69.4,2019,puskesmas
10,Kabupaten Sumedang,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,2019,puskesmas
11,Kabupaten Indramayu,2615,1223,46.8,18290,699.4,0,0,606,0,0.0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,2019,puskesmas
12,Kabupaten Subang,4451,910,20.4,1808,40.6,157859,152119,309978,27633,17.5,29115,19.1,56748,18.3,7326,7617,14943,3759,51.3,3788,49.7,7547,50.5,2019,puskesmas
13,Kabupaten Purwakarta,477,381,79.9,449,94.1,45970,41894,87864,26631,57.9,28620,68.3,55251,62.9,9612,8982,18594,6605,68.7,6535,72.8,13140,70.7,2019,puskesmas
14,Kabupaten Karawang,742,414,55.8,742,100.0,80183,75724,155907,28690,35.8,28048,37.0,56738,36.4,12118,11857,23975,7001,57.8,7076,59.7,14077,58.7,2019,puskesmas
15,Kabupaten Bekasi,2685,514,19.1,2273,84.7,102697,108400,211097,37144,36.2,39225,36.2,76369,36.2,15193,15453,30646,7568,49.8,7967,51.6,15535,50.7,2019,puskesmas
16,Kabupaten Bandung Barat,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,2019,puskesmas
17,Kabupaten Pangandaran,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,2019,puskesmas
18,Kota Bogor,337,315,93.5,332,98.5,44702,43316,88018,26488,59.3,27028,62.4,53516,60.8,13191,12678,25869,7365,55.8,8459,66.7,15824,61.2,2019,puskesmas
19,Kota Sukabumi,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,2019,puskesmas
20,Kota Bandung,526,457,86.9,414,78.7,82033,87673,169706,47525,57.9,52204,59.5,99729,58.8,17267,19473,36740,6543,37.9,8366,43.0,14909,40.6,2019,puskesmas
21,Kota Cirebon,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,2019,puskesmas
22,Kota Bekasi,821,42,5.1,42,5.1,11388,11620,23008,3063,26.9,3217,27.7,6280,27.3,409,521,930,153,37.4,154,29.6,307,33.0,2019,puskesmas
23,Kota Depok,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,2019,puskesmas
24,Kota Cimahi,149,176,118.1,263,176.5,34832,32970,67802,18744,53.8,18438,55.9,37182,54.8,8074,8105,16179,1377,17.1,1570,19.4,2947,18.2,2019,puskesmas
25,Kota Tasikmalaya,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,0,0.0,2019,puskesmas
26,Kota Banjar,111,86,77.5,94,84.7,10099,9242,19341,1672,16.6,1629,17.6,3301,17.1,0,0,0,0,0.0,0,0.0,0,0.0,2019,puskesmas
27,Jawa Barat,27939,13169,47.1,40049,143.3,980671,915813,2028382,555821,56.7,502421,54.9,1133753,55.9,176196,179604,370890,79293,45.0,84570,47.1,174190,47.0,2019,puskesmas

In [57]:
## Jumlah Tenaga Medis Per Kab/Kota Puskesmas
tables = camelot.read_pdf("2019.pdf", flavor='stream', pages='163')

df = tables[0].df

df = df.iloc[:32, [1] + [21,23,25,27,29,31]]

df = df.iloc[5: ]
df.set_axis(['Kab/Kota','jml_dg_l','jml_dg_p','jml_dg_lp','jml_dgsp_l','jml_dgsp_p','jml_dgsp_lp'], axis=1, inplace=True)
df = df.replace('', '0')
df = df.replace('-', '0')

for col in df.columns[~(df.columns.str.contains('%') | (df.columns == 'Kab/Kota'))]:
    df[col] = df[col].str.replace(',', '').astype(int)
df

,Kab/Kota,jml_dg_l,jml_dg_p,jml_dg_lp,jml_dgsp_l,jml_dgsp_p,jml_dgsp_lp
5,Kabupaten Bogor,5,56,61,0,0,0
6,Kabupaten Sukabumi,8,13,21,0,0,0
7,Kabupaten Cianjur,5,27,32,0,0,0
8,Kabupaten Bandung,13,61,74,0,0,0
9,Kabupaten Garut,8,19,27,0,0,0
10,Kabupaten Tasikmalaya,7,16,23,0,0,0
11,Kabupaten Ciamis,4,12,16,0,0,0
12,Kabupaten Kuningan,5,10,15,0,0,0
13,Kabupaten Cirebon,9,27,36,0,0,0
14,Kabupaten Majalengka,4,14,18,0,0,0
15,Kabupaten Sumedang,4,9,13,0,0,0
16,Kabupaten Indramayu,4,19,23,0,0,0
17,Kabupaten Subang,1,18,19,0,0,0
18,Kabupaten Purwakarta,4,15,19,0,0,0
19,Kabupaten Karawang,7,26,33,0,0,0
20,Kabupaten Bekasi,4,39,43,0,0,0
21,Kabupaten Bandung Barat,6,25,31,0,0,0
22,Kabupaten Pangandaran,3,6,9,0,0,0
23,Kota Bogor,2,41,43,0,0,0
24,Kota Sukabumi,4,5,9,0,0,0
25,Kota Bandung,13,94,107,0,0,0
26,Kota Cirebon,3,18,21,0,0,0
27,Kota Bekasi,3,70,73,0,0,0
28,Kota Depok,1,50,51,0,0,0
29,Kota Cimahi,0,16,16,0,0,0
30,Kota Tasikmalaya,5,17,22,0,0,0
31,Kota Banjar,1,3,4,0,0,0

In [58]:
# Menggabungkan kolom 'jml_dg_l', 'jml_dg_p', 'jml_dgsp_l', dan 'jml_dgsp_p' menjadi satu kolom 'jumlah'
df_dg = pd.concat([
    df.loc[:,['Kab/Kota','jml_dg_l']].rename(columns={'jml_dg_l':'jumlah'}).assign(jns_kelamin='laki-laki', profesi='dokter gigi', unit_kerja='puskesmas'),
    df.loc[:,['Kab/Kota','jml_dg_p']].rename(columns={'jml_dg_p':'jumlah'}).assign(jns_kelamin='perempuan', profesi='dokter gigi', unit_kerja='puskesmas'),
    df.loc[:,['Kab/Kota','jml_dgsp_l']].rename(columns={'jml_dgsp_l':'jumlah'}).assign(jns_kelamin='laki-laki', profesi='dokter gigi spesialis', unit_kerja='puskesmas'),
    df.loc[:,['Kab/Kota','jml_dgsp_p']].rename(columns={'jml_dgsp_p':'jumlah'}).assign(jns_kelamin='perempuan', profesi='dokter gigi spesialis', unit_kerja='puskesmas')
], ignore_index=True)

# Menghapus duplikat dan mengurutkan data berdasarkan 'Kab/Kota' dan 'jns_kelamin'
df_dg = df_dg.drop_duplicates().sort_values(['Kab/Kota','jns_kelamin'])
df_dg['tahun'] = "2019"
df_dg

,Kab/Kota,jumlah,jns_kelamin,profesi,unit_kerja,tahun
3,Kabupaten Bandung,13,laki-laki,dokter gigi,puskesmas,2019
57,Kabupaten Bandung,0,laki-laki,dokter gigi spesialis,puskesmas,2019
30,Kabupaten Bandung,61,perempuan,dokter gigi,puskesmas,2019
84,Kabupaten Bandung,0,perempuan,dokter gigi spesialis,puskesmas,2019
16,Kabupaten Bandung Barat,6,laki-laki,dokter gigi,puskesmas,2019
...,...,...,...,...,...,...
100,Kota Sukabumi,0,perempuan,dokter gigi spesialis,puskesmas,2019
25,Kota Tasikmalaya,5,laki-laki,dokter gigi,puskesmas,2019
79,Kota Tasikmalaya,0,laki-laki,dokter gigi spesialis,puskesmas,2019
52,Kota Tasikmalaya,17,perempuan,dokter gigi,puskesmas,2019
106,Kota Tasikmalaya,0,perempuan,dokter gigi spesialis,puskesmas,2019

In [61]:
## Jumlah Tenaga Medis Kab/Kota Rumah Sakit

tables = camelot.read_pdf("2019.pdf", flavor='stream', pages='163')

df = tables[0].df

df = df.iloc[33:, [1] + [21,23,25,27,29,31]]


df.set_axis(['Kab/Kota','jml_dg_l','jml_dg_p','jml_dg_lp','jml_dgsp_l','jml_dgsp_p','jml_dgsp_lp'], axis=1, inplace=True)
df = df.replace('', '0')
df = df.replace('-', '0')

for col in df.columns[~(df.columns.str.contains('%') | (df.columns == 'Kab/Kota'))]:
    df[col] = df[col].str.replace(',', '').astype(int)
    
df

,Kab/Kota,jml_dg_l,jml_dg_p,jml_dg_lp,jml_dgsp_l,jml_dgsp_p,jml_dgsp_lp
33,Kabupaten Bogor,4,13,17,5,10,15
34,Kabupaten Sukabumi,6,13,19,3,1,4
35,Kabupaten Cianjur,2,7,9,1,3,4
36,Kabupaten Bandung,3,9,12,2,5,7
37,Kabupaten Garut,0,3,3,0,2,2
38,Kabupaten Tasikmalaya,2,1,3,0,0,0
39,Kabupaten Ciamis,2,4,6,0,2,2
40,Kabupaten Kuningan,4,7,11,0,1,1
41,Kabupaten Cirebon,2,5,7,1,3,4
42,Kabupaten Majalengka,1,6,7,0,0,0
43,Kabupaten Sumedang,0,2,2,0,0,0

In [67]:
tables = camelot.read_pdf("2019.pdf", flavor='stream', pages='164')

df2 = tables[0].df

df2 = df2.iloc[:31, [1] + [21,23,25,27,29,31]]
df2 = df2.iloc[3:]
df2.set_axis(['Kab/Kota','jml_dg_l','jml_dg_p','jml_dg_lp','jml_dgsp_l','jml_dgsp_p','jml_dgsp_lp'], axis=1, inplace=True)
df2 = df2.replace('', '0')
df2 = df2.replace('-', '0')

for col in df2.columns[~(df2.columns.str.contains('%') | (df2.columns == 'Kab/Kota'))]:
    df2[col] = df2[col].str.replace(',', '').astype(int)

df2
df = pd.concat([df, df2], ignore_index=True)

In [68]:
df_dg = pd.concat([
    df.loc[:,['Kab/Kota','jml_dg_l']].rename(columns={'jml_dg_l':'jumlah'}).assign(jns_kelamin='laki-laki', profesi='dokter gigi', unit_kerja='rumah sakit'),
    df.loc[:,['Kab/Kota','jml_dg_p']].rename(columns={'jml_dg_p':'jumlah'}).assign(jns_kelamin='perempuan', profesi='dokter gigi', unit_kerja='rumah sakit'),
    df.loc[:,['Kab/Kota','jml_dgsp_l']].rename(columns={'jml_dgsp_l':'jumlah'}).assign(jns_kelamin='laki-laki', profesi='dokter gigi spesialis', unit_kerja='rumah sakit'),
    df.loc[:,['Kab/Kota','jml_dgsp_p']].rename(columns={'jml_dgsp_p':'jumlah'}).assign(jns_kelamin='perempuan', profesi='dokter gigi spesialis', unit_kerja='rumah sakit')
], ignore_index=True)

# Menghapus duplikat dan mengurutkan data berdasarkan 'Kab/Kota' dan 'jns_kelamin'
df_dg = df_dg.drop_duplicates().sort_values(['Kab/Kota','jns_kelamin'])
df['tahun'] = "2019"
df_dg

,Kab/Kota,jumlah,jns_kelamin,profesi,unit_kerja
3,Kabupaten Bandung,3.0,laki-laki,dokter gigi,rumah sakit
143,Kabupaten Bandung,2.0,laki-laki,dokter gigi spesialis,rumah sakit
73,Kabupaten Bandung,9.0,perempuan,dokter gigi,rumah sakit
213,Kabupaten Bandung,5.0,perempuan,dokter gigi spesialis,rumah sakit
60,Kabupaten Bandung Barat,6.0,laki-laki,dokter gigi,rumah sakit
...,...,...,...,...,...
278,Kota Tasikmalaya,5.0,perempuan,dokter gigi spesialis,rumah sakit
11,NaN,NaN,laki-laki,dokter gigi,rumah sakit
151,NaN,NaN,laki-laki,dokter gigi spesialis,rumah sakit
81,NaN,NaN,perempuan,dokter gigi,rumah sakit
221,NaN,NaN,perempuan,dokter gigi spesialis,rumah sakit

In [70]:
# ## Klinik DIKLAT KESEHATAN
data_bogor = {'Kab/Kota': 'Kabupaten Bogor',
              'jml_dg_l': 0,
              'jml_dg_p': 1,
              'jml_dgsp_l': 0,
              'jml_dgsp_p': 0}

data_garut = {'Kab/Kota': 'Kabupaten Garut',
                'jml_dg_l': 1,
                'jml_dg_p': 0,
                'jml_dgsp_l': 0,
                'jml_dgsp_p': 0}

df_bogor = pd.DataFrame([data_bogor])
df_garut = pd.DataFrame([data_garut])

df_combined = pd.concat([df_bogor, df_garut], ignore_index=True)

df_dg = pd.concat([
    df_combined.loc[:,['Kab/Kota','jml_dg_l']].rename(columns={'jml_dg_l':'jumlah'}).assign(jns_kelamin='laki-laki', profesi='dokter gigi', unit_kerja='klinik diklat kesehatan'),
    df_combined.loc[:,['Kab/Kota','jml_dg_p']].rename(columns={'jml_dg_p':'jumlah'}).assign(jns_kelamin='perempuan', profesi='dokter gigi', unit_kerja='klinik diklat kesehatan'),
    df_combined.loc[:,['Kab/Kota','jml_dgsp_l']].rename(columns={'jml_dgsp_l':'jumlah'}).assign(jns_kelamin='laki-laki', profesi='dokter gigi spesialis', unit_kerja='klinik diklat kesehatan'),
    df_combined.loc[:,['Kab/Kota','jml_dgsp_p']].rename(columns={'jml_dgsp_p':'jumlah'}).assign(jns_kelamin='perempuan', profesi='dokter gigi spesialis', unit_kerja='klinik diklat kesehatan')
], ignore_index=True)

# Menghapus duplikat dan mengurutkan data berdasarkan 'Kab/Kota' dan 'jns_kelamin'
df_dg = df_dg.drop_duplicates().sort_values(['Kab/Kota','jns_kelamin'])
df['tahun'] = "2019"
df_dg

,Kab/Kota,jumlah,jns_kelamin,profesi,unit_kerja
0,Kabupaten Bogor,0,laki-laki,dokter gigi,klinik diklat kesehatan
4,Kabupaten Bogor,0,laki-laki,dokter gigi spesialis,klinik diklat kesehatan
2,Kabupaten Bogor,1,perempuan,dokter gigi,klinik diklat kesehatan
6,Kabupaten Bogor,0,perempuan,dokter gigi spesialis,klinik diklat kesehatan
1,Kabupaten Garut,1,laki-laki,dokter gigi,klinik diklat kesehatan
5,Kabupaten Garut,0,laki-laki,dokter gigi spesialis,klinik diklat kesehatan
3,Kabupaten Garut,0,perempuan,dokter gigi,klinik diklat kesehatan
7,Kabupaten Garut,0,perempuan,dokter gigi spesialis,klinik diklat kesehatan

In [69]:
## Klinik Dinas Kesehatan
### Data 0 semua

          Kab/Kota  jumlah jns_kelamin                profesi     unit_kerja
0  Kabupaten Bogor       0   laki-laki            dokter gigi  klinik DINKES
4  Kabupaten Bogor       0   laki-laki  dokter gigi spesialis  klinik DINKES
2  Kabupaten Bogor       1   perempuan            dokter gigi  klinik DINKES
6  Kabupaten Bogor       0   perempuan  dokter gigi spesialis  klinik DINKES
1  Kabupaten Garut       1   laki-laki            dokter gigi  klinik DINKES
5  Kabupaten Garut       0   laki-laki  dokter gigi spesialis  klinik DINKES
3  Kabupaten Garut       0   perempuan            dokter gigi  klinik DINKES
7  Kabupaten Garut       0   perempuan  dokter gigi spesialis  klinik DINKES

# Data Tahap 1

In [5]:
def check_for_jabatan(page):
    '''
    Fungsi untuk mengecek keberadaan informasi jurusan pilihan
    Input: page (ex: pdf.pages[0])
    Output: 
        - dicitionary berisi informasi jurusan pilihan
    '''
    if "Jumlah Tenaga Kesehatan di Puskesmas" in page.extract_text():
        text = pg.extract_text()
        pendidikan = pg.extract_tables()[1][0][1]
        jurusan_strings = text.split("Jurusan : ")[1].split("Lokasi")[0]
        lokasi_front = ""
        jurusan = jurusan_strings.split("\n")[0]

        lokasi_string = text.split("Lokasi Formasi : ")[1].split("Jenis")[0]

        return {
            "kode_jurusan": jurusan.split(" - ")[0],
            "jurusan": jurusan.split(" - ")[1],
            "kode_lokasi": lokasi_string.split(" - ")[0],
            "lokasi_formasi": lokasi_string.split(" - ")[1].split("\n")[0],
            "pendidikan": pendidikan.replace("\n", " ")
        }
    else:
        return {}

def check_for_detail_tables(page):
    '''
    Fungsi untuk mengecek keberadaan tabel perorangan
    Input: page (ex: pdf.pages[0])
    Output: 
        - found (binary, iya tidaknya sebuah halaman punya tabel perorangan)
        - df_returned (tabel perorangan jika ada)
    '''
    found = False
    df_returned = pd.DataFrame()
    for table in pg.extract_tables():
        df = pd.DataFrame(table)

        if (df.shape[1] == 9): #jumlah kolom = 9 
            found = True
            df_returned = df
    return found, df_returned


def split_df(df_):
    '''
    Fungsi untuk split tabel perorangan. Kadang ada satu halaman dengan lebih dari satu tabel.
    Input: df_ (dataframe tabel perorangan)
    Output: 
        - list berisi beberapa dataframe untuk tiap individu
    '''
    dfs = []
    header_indexes = list(df_[df_[1]=="No Peserta"].index)
    header_indexes.append(len(df_))
    for i in range(len(header_indexes)-1):
        splitted_df = df_.iloc[header_indexes[i]: header_indexes[i+1], :]
        splitted_df.index = range(len(splitted_df))
        dfs.append(splitted_df)
    return dfs

def get_info_from_table(df_, idx):
    '''
    Fungsi untuk mengekstrak informasi dari tabel perorangan 
    Input: df_ (dataframe tabel perorangan)
    Output: 
        - dicitionary berisi informasi perorangan yang telah diekstrak
    '''
    base_data =  {
        "no_peserta": df_.iloc[idx,1],
        "kode_pendidikan": df_.iloc[idx,2],
        "total_twk": df_.iloc[idx,4],
        "total_tiu": df_.iloc[idx,5],
        "total_tkp": df_.iloc[idx,6],
        "total_skd": df_.iloc[idx,7],
        "keterangan": df_.iloc[idx,8]
    }

    return {**base_data}

In [7]:
start_index = 0
end_index = 929
pdf = pdfplumber.open('datasets/Lampiran B-099.02720.06.2022 Pengumuman Hasil Tahap 1 Tahun 2022.pdf')

# start iterating
result = []
last_jabatan = {}

start_time = dt.datetime.now()
start_time = dt.datetime.now()
for i in range(start_index, end_index):
    pg = pdf.pages[i]

    # jika halaman tsb ada info tentang lowongan, simpan
    current_jabatan = check_for_jabatan(pg)
    if current_jabatan != {}:
        last_jabatan = current_jabatan
    
    is_detail_found, detail_df = check_for_detail_tables(pg)
    # jika ketemu ada tabel perorangan
    if is_detail_found:
        splitted_df = split_df(detail_df)
        for df_ in splitted_df:
            for i in range(2, len(df_)):
                details = get_info_from_table(df_, i)
                if current_jabatan == {}:
                    # kalo ada info lowongan di halaman yang sama, pakai info lowongan tsb
                    details.update(last_jabatan)
                else:
                    # kalo ga, pake info lowongan terakhir
                    details.update(current_jabatan)
                    last_jabatan = current_jabatan
                result.append(details)

    # untuk logging
    if i%100 == 99:
        curr_time = dt.datetime.now()
        print("Done for "+str(i), curr_time-start_time)
        start_time = dt.datetime.now()

res = pd.DataFrame(result)

OSError: [Errno 22] Invalid argument: 'spmb_0_929_2024-02-18 13:35:49.467388.csv'

In [9]:
res.to_csv('Tahap 1.csv')